title: Fujima Electronics
description: Fujima Electronics's Github Page
#theme: just-the-docs
remote_theme: just-the-docs

#url: https://just-the-docs.github.io
baseurl: ""
url: https://fujimaelectronics.github.io/

exclude:
  - assets/

favicon_ico: /assets/img/favicon.ico
nav_enabled: true
